export const changeProfilePasswordConstants = {
    CHANGE_PROFILE_PASSWORD: 'CHANGE_PROFILE_PASSWORD',
    CHANGE_PROFILE_PASSWORD_LOADING: 'CHANGE_PROFILE_PASSWORD_LOADING',
    CHANGE_PROFILE_PASSWORD_SUCCESS: 'CHANGE_PROFILE_PASSWORD_SUCCESS',
    CHANGE_PROFILE_PASSWORD_FAILURE: 'CHANGE_PROFILE_PASSWORD_FAILURE',
    CHANGE_PROFILE_PASSWORD_RESET: 'CHANGE_PROFILE_PASSWORD_RESET',
};
